### ISSUE TITLE
Update pass-indexer to support both the ES completion suggester and the pass modified completion suggester 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-indexer#16]
Perform necessary update to pass-indexer so that it can work with user objects being suggested using the regular ES completion suggester AND the journal object being suggested using the  pass modified completion suggester .

MOre details in this discussion document

**Comment by markpatton** [comment]
Passed tests in travis. The pr needs review. See the questions in it.

**Comment by htpvu** [comment]
We decided to take a different direction in searching for users.
