### ISSUE TITLE
pass-indexer must be supplied a index configuration location

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-indexer#24]
Outcome of this discussion https://docs.google.com/document/d/1BemWL76fnC_nLq5UypnnaUmLpu829hcg8UC7cyy0kbQ/edit#

**Comment by emetsger** [comment]
.5 LE

**Comment by markpatton** [comment]
Looking at the discussion it seems like this issue should really be removing the ability of pass-indexer to create an index when it does not exist.

**Comment by emetsger** [comment]
![pass indexer workflow](https://user-images.githubusercontent.com/146970/53196556-5f5a1480-35e6-11e9-8cc6-b36310a4e924.png)

**Comment by emetsger** [comment]
The notion here is that pass-indexer is _always_ provided two things: a URL to an index, and a URL to an index configuration. 

if the index already exists, then the supplied index configuration is ignored, and it is read from the existing index.

if the index does not exist, pass-indexer creates the index using the supplied configuration.

**Comment by emetsger** [comment]
If pass-indexer is missing any of the required provided parameters:
- the URL to an index
- the URL to the index configuration

it should abort.
