### ISSUE TITLE
Update ITs as necessary  after some update in pass-indexer code as part of the effort to simplify the data model update process

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-indexer#25]
More context here https://docs.google.com/document/d/1BemWL76fnC_nLq5UypnnaUmLpu829hcg8UC7cyy0kbQ/edit#

Particularly
check on the IT with hardcoded in context url - make sure that the mapping matches with the context - making sure the IT set the config file location env var to use the same file as the indexer (PassIndexerIT#setup(), PassIndexerIT#create_pass_object(...))

**Comment by emetsger** [comment]
.5 LE
